import{S as d}from"./assets/vendor-B84wOYCN.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const h="48337516-7b7bbb1aa3939e40fc99ef59c",y="https://pixabay.com/api/";async function f(t,o,i){const n=`${y}?key=${h}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=${i}`,e=await fetch(n);if(!e.ok)throw new Error("Failed to fetch images");return await e.json()}function b({webformatURL:t,largeImageURL:o,tags:i,likes:n,views:e,comments:r,downloads:s}){return`
      <a href="${o}" class="gallery-item">
        <img src="${t}" alt="${i}" loading="lazy" />
        <div class="info">
          <p class="info-item"><span>Likes</span><b>${n}</b></p>
          <p class="info-item"><span>Views</span><b>${e}</b></p>
          <p class="info-item"><span>Comments</span><b>${r}</b></p>
          <p class="info-item"><span>Downloads</span><b>${s}</b></p>
        </div>
      </a>
    `}const w=document.querySelector("#search-form"),p=document.querySelector(".gallery");let l="",a=1;const m=40;let u,c=!1;w.addEventListener("submit",P);window.addEventListener("scroll",$);function L(){iziToast.error({title:"",message:"Sorry, there are no images matching<br>your search query. Please, try again!",position:"topRight",timeout:5e3,backgroundColor:"#f14646",class:"custom-toast"})}async function P(t){t.preventDefault();const o=t.currentTarget.elements.searchQuery.value.trim();if(!o){iziToast.error({title:"Error",message:"Please enter a search query.",position:"topRight",timeout:3e3});return}l=o,a=1,S();try{const i=await f(l,a,m);if(i.hits.length===0){L();return}g(i.hits),u=new d(".gallery a"),u.refresh()}catch{iziToast.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight",timeout:3e3})}}async function $(){if(window.innerHeight+window.scrollY>=document.body.offsetHeight-100&&!c){c=!0,a+=1;try{const t=await f(l,a,m);t.hits.length>0?(g(t.hits),u.refresh()):iziToast.info({title:"Info",message:"No more images to load.",position:"topRight",timeout:3e3})}catch{iziToast.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight",timeout:3e3})}finally{c=!1}}}function g(t){const o=t.map(b).join("");p.insertAdjacentHTML("beforeend",o)}function S(){p.innerHTML=""}
//# sourceMappingURL=index.js.map
