import{S as f}from"./assets/vendor-B84wOYCN.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const p="48337516-7b7bbb1aa3939e40fc99ef59c",m="https://pixabay.com/api/";async function d(o,r,n){const s=`${m}?key=${p}&q=${encodeURIComponent(o)}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${n}`,e=await fetch(s);if(!e.ok)throw new Error("Failed to fetch images");return await e.json()}function y({webformatURL:o,largeImageURL:r,tags:n,likes:s,views:e,comments:t,downloads:a}){return`
      <a href="${r}" class="gallery-item">
        <img src="${o}" alt="${n}" loading="lazy" />
        <div class="info">
          <p class="info-item"><span>Likes</span><b>${s}</b></p>
          <p class="info-item"><span>Views</span><b>${e}</b></p>
          <p class="info-item"><span>Comments</span><b>${t}</b></p>
          <p class="info-item"><span>Downloads</span><b>${a}</b></p>
        </div>
      </a>
    `}const h=document.querySelector("#search-form"),u=document.querySelector(".gallery");let i="",c=1;const g=40;let l;function b(){document.querySelector(".loader").style.display="block"}function w(){document.querySelector(".loader").style.display="none"}h.addEventListener("submit",L);async function L(o){o.preventDefault();const r=o.currentTarget.elements.searchQuery.value.trim();if(!r){iziToast.error({title:"Error",message:"Please enter a search query.",position:"topRight",timeout:3e3});return}i=r,c=1,P(),b();try{const n=await d(i,c,g);if(n.hits.length===0){S();return}$(n.hits),l=new f(".gallery a"),l.refresh()}catch{iziToast.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight",timeout:3e3})}finally{w()}}function $(o){const r=o.map(y).join("");u.insertAdjacentHTML("beforeend",r)}function P(){u.innerHTML=""}function S(){iziToast.error({title:"",message:"Sorry, there are no images matching<br>your search query. Please, try again!",position:"topRight",timeout:5e3,backgroundColor:"#f14646",class:"custom-toast"})}
//# sourceMappingURL=index.js.map
